---
name: "Kitsu release"

on:
  push:
    push:
      branches: master
    tags:
      - '*'

jobs:
  make_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build release
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
        run: |
          npm ci
          npm run build
          GIT_COMMIT="$(git rev-parse HEAD)"
          GIT_TAG="$(git describe --tags)"
          KITSU_VERSION="$(echo ${GIT_TAG} | sed 's/^v//;s/-build//')"
          echo "${KITSU_VERSION}" > dist/.version.txt
          echo "${GIT_COMMIT}"    > dist/.commit.txt
          echo "${GIT_TAG}"       > dist/.tag.txt
          CHECKSUM_FILENAME="kitsu-${KITSU_VERSION}.SHA512"
          ARTEFACT_FILENAME="kitsu-${KITSU_VERSION}.tgz"
          (cd dist && tar cvzf "../${ARTEFACT_FILENAME}" .)
          sha512sum "${ARTEFACT_FILENAME}" > "${CHECKSUM_FILENAME}"
      - name: Create release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          artifacts: "kitsu-*.tgz,kitsu-*.SHA512"
          token: ${{ secrets.GITHUB_TOKEN }}
