name: "Kitsu release"

on:
  push:
    push:
      branches: master
    tags:
      - '*'
jobs:
  make_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          npm install
          npm run build
      - name: version
        run: echo "::set-output name=version::$(git describe --tags)"
        id: version
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
